version: '2'

services:
    web:
        build: ./web
        container_name: project-name-web
        image: project-name-web
        ports:
            - ${APP_PORT}:80
            - ${APP_PORT_SECURE}:443
        volumes:
            - ${APP_DIR}:/home/app:ro
        links:
            - php
        network_mode: bridge

    php:
        container_name: project-name-php
        image: aciliadevops/dev-php-fpm-8.0
        links:
            - db
            - mailcatcher
        volumes:
            - ${APP_DIR}:/home/app:cached
        network_mode: bridge
        working_dir: /home/app

    db:
        build: ./dbserver
        container_name: project-name-db
        image: project-name-db
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ${APP_DB}:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        network_mode: bridge

    mailcatcher:
        container_name: project-name-mail
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
        network_mode: bridge
